### ISSUE TITLE
'imagine' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by jdqw210** [lucidrains/deep-daze#140]
'imagine' is not recognized as an internal or external command,
operable program or batch file.

I can't run 'imagine' it just gives me this error... any help?

**Comment by jdqw210** [comment]
now it's just 

C:\Users\Justin\AppData\Roaming\Python\Python39\site-packages\deep_daze>python -m deep_daze.py
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Justin\AppData\Roaming\Python\Python39\site-packages\deep_daze\deep_daze.py", line 23, in <module>
    from .clip import load, tokenize
ImportError: attempted relative import with no known parent package
