### ISSUE TITLE
PyTorch error: TypeError: meshgrid() got an unexpected keyword argument 'indexing'

### ISSUE THREAD

**Issue by thelabcat** [lucidrains/deep-daze#194]
```
PS C:\Users\zargu\imagine> imagine "spacecraft repair shop"
Setting jit to False because torch version is not 1.7.1.
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\imagine.exe\__main__.py", line 7, in <module>
  File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deep_daze\cli.py", line 151, in main
    fire.Fire(train)
  File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deep_daze\cli.py", line 99, in train
    imagine = Imagine(
  File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deep_daze\deep_daze.py", line 354, in __init__
    model = DeepDaze(
  File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deep_daze\deep_daze.py", line 169, in __init__
    self.model = SirenWrapper(
  File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\siren_pytorch\siren_pytorch.py", line 137, in __init__
    mgrid = torch.stack(torch.meshgrid(*tensors, indexing = 'ij'), dim=-1)
TypeError: meshgrid() got an unexpected keyword argument 'indexing'
```

**Comment by NotAnNvidiaFan** [comment]
I was able to fix this issue by changing my version of pytorch to version 1.10.2

**Comment by elonerajeev** [comment]
> ```
> PS C:\Users\zargu\imagine> imagine "spacecraft repair shop"
> Setting jit to False because torch version is not 1.7.1.
> Traceback (most recent call last):
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\imagine.exe\__main__.py", line 7, in <module>
>   File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deep_daze\cli.py", line 151, in main
>     fire.Fire(train)
>   File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 466, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deep_daze\cli.py", line 99, in train
>     imagine = Imagine(
>   File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deep_daze\deep_daze.py", line 354, in __init__
>     model = DeepDaze(
>   File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deep_daze\deep_daze.py", line 169, in __init__
>     self.model = SirenWrapper(
>   File "C:\Users\zargu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\siren_pytorch\siren_pytorch.py", line 137, in __init__
>     mgrid = torch.stack(torch.meshgrid(*tensors, indexing = 'ij'), dim=-1)
> TypeError: meshgrid() got an unexpected keyword argument 'indexing'
> ```
