### ISSUE TITLE
TypeError: '<=' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by LJBoxx** [lucidrains/deep-daze#200]
C:\Users\User>imagine a jasmine flower
Setting jit to False because torch version is not 1.7.1.
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\imagine.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\deep_daze\cli.py", line 151, in main
    fire.Fire(train)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\deep_daze\cli.py", line 99, in train
    imagine = Imagine(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\deep_daze\deep_daze.py", line 380, in __init__
    self.optimizer = AdamP(siren_params, lr)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\torch_optimizer\adamp.py", line 57, in __init__
    if lr <= 0.0:
TypeError: '<=' not supported between instances of 'str' and 'float'

**Comment by LJBoxx** [comment]
Nevermind just put quotes...
