### ISSUE TITLE
Missing import `random` when trying to use a seed`

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/deep-daze#27]
```bash
Traceback (most recent call last):
  File "/home/landon/.virtualenvs/deep-daze-afiaka/bin/imagine", line 11, in <module>
    load_entry_point('deep-daze==0.3.2', 'console_scripts', 'imagine')()
  File "/home/landon/.virtualenvs/deep-daze-afiaka/lib/python3.8/site-packages/deep_daze-0.3.2-py3.8.egg/deep_daze/cli.py", line 69, in main
    fire.Fire(train)
  File "/home/landon/.virtualenvs/deep-daze-afiaka/lib/python3.8/site-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/landon/.virtualenvs/deep-daze-afiaka/lib/python3.8/site-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/landon/.virtualenvs/deep-daze-afiaka/lib/python3.8/site-packages/fire-0.4.0-py3.8.egg/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/landon/.virtualenvs/deep-daze-afiaka/lib/python3.8/site-packages/deep_daze-0.3.2-py3.8.egg/deep_daze/cli.py", line 46, in train
    imagine = Imagine(
  File "/home/landon/.virtualenvs/deep-daze-afiaka/lib/python3.8/site-packages/deep_daze-0.3.2-py3.8.egg/deep_daze/deep_daze.py", line 216, in __init__
    random.seed(seed)
NameError: name 'random' is not defined
```

Not sure which `random` this is supposed to be. Is it python's random or torch.random? Happy to fix it.

**Comment by afiaka87** [comment]
```python
        if exists(seed):
            print(f'setting seed: {seed}')
            torch.manual_seed(seed)
            torch.cuda.manual_seed(seed)
            random.seed(seed) # This `random` hasn't been imported
            torch.backends.cudnn.deterministic = True
```

**Comment by lucidrains** [comment]
@afiaka87 thanks for catching this! https://github.com/lucidrains/deep-daze/releases/tag/0.3.3
