### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by 24mjihad** [lucidrains/deep-daze#68]
I have installed the pip and installed CUDA but when I run this happens, any idea on what's the problem. I'm new to coding so I have no idea.

(base) PS C:\Users\jihad> imagine "a house in the forest"
Traceback (most recent call last):
  File "c:\users\jihad\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jihad\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jihad\anaconda3\Scripts\imagine.exe\__main__.py", line 4, in <module>
  File "c:\users\jihad\anaconda3\lib\site-packages\deep_daze\__init__.py", line 1, in <module>
    from deep_daze.deep_daze import DeepDaze, Imagine
  File "c:\users\jihad\anaconda3\lib\site-packages\deep_daze\deep_daze.py", line 25, in <module>
    assert torch.cuda.is_available(), 'CUDA must be available in order to use Deep Daze'
AssertionError: CUDA must be available in order to use Deep Daze

**Comment by 24mjihad** [comment]
I did import torch
torch.cuda.is_available() 
and it came back false what do I do :(

**Comment by bytehut** [comment]
I was able to solve this issue by downloading pytorch from their site [here](https://pytorch.org/get-started/locally/). I used CUDA 11.1 and the error disappeared, but I'm still having trouble with [Method 'forward' is not defined](https://github.com/lucidrains/deep-daze/issues/67#issue-823718686).

**Comment by mroosen** [comment]
Are you guys using a fresh (anaconda) environment?

@24mjihad which videocard do you have?

**Comment by 24mjihad** [comment]
@bytehut I will try that, @mroosen no I don't, do you think that's the problem? I have the rtx 3060 ti

**Comment by 24mjihad** [comment]
I install pytorch but now I get this error


(base) PS C:\Users\jihad> imagine "space mushroom"
Traceback (most recent call last):
  File "c:\users\jihad\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jihad\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jihad\anaconda3\Scripts\imagine.exe\__main__.py", line 4, in <module>
  File "c:\users\jihad\anaconda3\lib\site-packages\deep_daze\__init__.py", line 1, in <module>
    from deep_daze.deep_daze import DeepDaze, Imagine
  File "c:\users\jihad\anaconda3\lib\site-packages\deep_daze\deep_daze.py", line 14, in <module>
    from torch.cuda.amp import GradScaler, autocast
ImportError: cannot import name 'autocast' from 'torch.cuda.amp' (c:\users\jihad\anaconda3\lib\site-packages\torch\cuda\amp\__init__.py)
(base) PS C:\Users\jihad>
