### ISSUE TITLE
AssertionError: CUDA unavaliable

### ISSUE THREAD

**Issue by AppleCraxkhead** [lucidrains/deep-daze#72]
This is definitely PEBKAC but whenever I run Imagine "x"  I get:
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\imagine.exe\__main__.py", line 4, in <module>
  File "c:\python39\lib\site-packages\deep_daze\__init__.py", line 1, in <module>
    from deep_daze.deep_daze import DeepDaze, Imagine
  File "c:\python39\lib\site-packages\deep_daze\deep_daze.py", line 25, in <module>
    assert torch.cuda.is_available(), 'CUDA must be available in order to use Deep Daze'
AssertionError: CUDA must be available in order to use Deep Daze

**Comment by AppleCraxkhead** [comment]
nvm I'm quite stupid and figured it out

**Comment by itsHNTR** [comment]
Im having the same issue. how did you fix it?

**Comment by AppleCraxkhead** [comment]
> Im having the same issue. how did you fix it?

yeah just do `pip uninstall torch` then go [here](https://pytorch.org/get-started/locally/) and select your OS etc, then run the command it gives u
