### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by PrivateServersGANG** [lucidrains/deep-daze#75]
Traceback (most recent call last):
  File "c:\users\marshall\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\marshall\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Marshall\AppData\Local\Programs\Python\Python38\Scripts\imagine.exe\__main__.py", line 4, in <module>
  File "c:\users\marshall\appdata\local\programs\python\python38\lib\site-packages\deep_daze\__init__.py", line 1, in <module>
    from deep_daze.deep_daze import DeepDaze, Imagine
  File "c:\users\marshall\appdata\local\programs\python\python38\lib\site-packages\deep_daze\deep_daze.py", line 25, in <module>
    assert torch.cuda.is_available(), 'CUDA must be available in order to use Deep Daze'
AssertionError: CUDA must be available in order to use Deep Daze

**Comment by JiriSuster** [comment]
Hi, try this:
`pip uninstall torch`
`pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by PrivateServersGANG** [comment]
Whenever i try to open the `torch-1.8.0+cu111-cp38-cp38-win_amd64.whl` file it instantly closes and i cant see what it says
